version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKER_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
           version: 20.10.14
           docker_layer_caching: true
      - run:
          |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t circleci-appdemo:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push circleci-appdemo:$TAG
      